### ISSUE TITLE
Unable to reinstall any github repository on windows

### ISSUE THREAD

**Issue by borysiasty** [QGIS-Contribution/QGIS-ResourceSharing#103]
This problem seems to be windows-specific (because of the single access to files on Windows?). On Linux it works fine.

If you try to reinstall any previously installed collection, Windows raise an access denied error related to a git index file in the downloaded repository. The message is something like (I'm re-typing from another machine):

[WinError 5] Access denied: xxx.idx.lock -> xxx.idx

where the xxx file is a blahblah-long-named file here: $QGIS_PROFILE$/resource_sharing/repositories/github.com/alinager/qgis-styles/.git/objects/pack

So it looks like the plugin tries to git clone, but git is already in use by a previous process?

Steps to reproduce:
1. Install any collection (e.g. Alina's Animal silhouettes)
2. Click "reinstall" (if it works, click reinstall again, as it seems sometimes the problem may occur at second reinstall).
3. The error pops up.

If you uninstall the collection and try to install again, the same happen, as uninstalling doesn't remove the git repo.

**Comment by havatv** [comment]
Thanks for reporting, @borysiasty.
I can confirm that this happens on Windows (Windows 10, QGIS 3.4, Resource Sharing 0.12.0). I have never experienced any such problems on Debian.

The Resource Sharing plugin is using the Dulwich library for github access, and I was hoping that upgrading Dulwich, as was done (to 0.19.5) with version 0.12.0 of the plugin, would fix this. Apparently not.
I tried again now, and got the WinError 5 after installing, and reinstalling the second time. I restarted the plugin and started it again.  I reinstalled the collection repeatedly, but was not able to get any WinError 5.
I restarted QGIS, installed the *Red Cross Emblems* collection and repeatedly reinstalled that collection without getting any WinError 5s.
Please report here if you have any suggestion for solving this issue!

**Comment by borysiasty** [comment]
Nope, I'm just a humble Debian user, too :( Just forwarding a report from Win users.

**Comment by havatv** [comment]
I have been testing the latest master, and have not seen any [WinError 5]s, so I close this issue now. Please re-open if the issue persists in version 0.13.0.

**Comment by havatv** [comment]
After testing some more, I was able to get the error on Windows 10 again.

After I got the error, I restarted QGIS, ran the plugin, and tried to install a collection (in this case *Animal silhouettes*). I then got:

`Error: [WinError 5] Access is denied: 'C:/Users/havatv/AppData/Roaming/QGIS/QGIS3\\profiles\\default/resource_sharing\\repositories\\github.com\\alinager\\qgis-styles\\.git\\objects\\pack\\pack-da39a3ee5e6b4b0d3255bfef95601890afd80709.idx.lock' -> 'C:/Users/havatv/AppData/Roaming/QGIS/QGIS3\\profiles\\default/resource_sharing\\repositories\\github.com\\alinager\\qgis-styles\\.git\\objects\\pack\\pack-da39a3ee5e6b4b0d3255bfef95601890afd80709.idx'`

From the *Log Messages* panel:
```
2020-04-10T07:12:56     WARNING    Traceback (most recent call last):
              File "C:/Users/havatv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGIS-ResourceSharing-master\resource_sharing\repository_handler\remote_git_handler.py", line 144, in download_collection
              errstream=writeOut
              File "C:\Users\havatv\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QGIS-ResourceSharing-master\ext_libs\dulwich\porcelain.py", line 954, in pull
              path, r, progress=errstream.write, determine_wants=determine_wants)
              File "C:\Users\havatv\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QGIS-ResourceSharing-master\ext_libs\dulwich\client.py", line 422, in fetch
              commit()
              File "C:\Users\havatv\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QGIS-ResourceSharing-master\ext_libs\dulwich\client.py", line 408, in commit
              target.object_store.add_thin_pack(f.read, None)
              File "C:\Users\havatv\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QGIS-ResourceSharing-master\ext_libs\dulwich\object_store.py", line 736, in add_thin_pack
              return self._complete_thin_pack(f, path, copier, indexer)
              File "C:\Users\havatv\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QGIS-ResourceSharing-master\ext_libs\dulwich\object_store.py", line 705, in _complete_thin_pack
              index_file.close()
              File "C:\Users\havatv\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QGIS-ResourceSharing-master\ext_libs\dulwich\file.py", line 175, in close
              os.replace(self._lockfilename, self._filename)
             PermissionError: [WinError 5] Access is denied: 'C:/Users/havatv/AppData/Roaming/QGIS/QGIS3\\profiles\\default/resource_sharing\\repositories\\github.com\\alinager\\qgis-styles\\.git\\objects\\pack\\pack-da39a3ee5e6b4b0d3255bfef95601890afd80709.idx.lock' -> 'C:/Users/havatv/AppData/Roaming/QGIS/QGIS3\\profiles\\default/resource_sharing\\repositories\\github.com\\alinager\\qgis-styles\\.git\\objects\\pack\\pack-da39a3ee5e6b4b0d3255bfef95601890afd80709.idx'
```

I was not able to install any collections - always got the same error.
So I quit QGIS and removed the *resource_sharing* folder under the QGIS user directory. I started QGIS again and ran the plugin. I then installed the same collection, reinstalled it a number of times, installed, uninstalled and reinstalled a number of other collections without getting any errors. I have not yet seen the error.

**Comment by havatv** [comment]
With version 0.14.1 of the plugin I have not seen any [WinError 5] errors yet on Microsoft Windows 10.

**Comment by borysiasty** [comment]
Thanks!

**Comment by havatv** [comment]
> Thanks!

Have your "Win users" tested the newest version of the plugin? Do they still experience problems?

**Comment by borysiasty** [comment]
No replicable anymore. Thanks!

**Comment by havatv** [comment]
> No replicable anymore. Thanks!

Thank you for confirming, @borysiasty!
