### ISSUE TITLE
Name of the downloaded resources

### ISSUE THREAD

**Issue by ghtmtt** [QGIS-Contribution/QGIS-ResourceSharing#110]
I think the name of the downloaded resources is very confusing for users. E.g. I just downloaded some SVGs from one of the main repository:

* the collection is placed within my profile as `/home/matteo/.local/share/QGIS/QGIS3/profiles/mat/resource_sharing/collections/33b75e8e0ac1ef736eae109d5d5de0697f4b2174`. I imagine that ` 33b75e8e0ac1ef736eae109d5d5de0697f4b2174` is an unique sha to avoid conflicts between folders with the same name. Not very intuitive for users though
* I can find the svg in QGIS within the folder with the same sha:

  ![immagine](https://user-images.githubusercontent.com/2884884/79730775-9cf12500-82f1-11ea-860c-28af0ebb71c0.png)

  I image a scenario where I've downloaded tens of resources (supposing just svg) and I'll struggle to find and remember the name of the folder of the svg I'm looking for.

Some ideas that comes into my mind:

* can the plugin look for existing folder, file, whatever, names and **if** the name name already exists than append a progressive `_1` to the downloaded resource? 
* if the name already exists than maybe create the folder as `repository_name` + `name_of_collection`?
* give the user the chance to edit the name of the downloaded collection afterwards

Hope this makes sense

**Comment by havatv** [comment]
This is definitely a problem. It is even documented :-) in http://qgis-contribution.github.io/QGIS-ResourceSharing/user/installing-collection.html:

> In addition, the collection will be added under the collections directory (for instance, resource_sharing/collections), with a, for most people, unintelligible name (the QGIS R script collection from the QGIS Official Repository is located in the resource_sharing/collections/8bc41c8c4fe90615b47eef7c81199fa6d7148fb3 directory).

Due Microsoft Windows issues with slashes in file names (#99), the collection name was removed from the directory name.
I hope we can find a way to get better directory (collection) names for display in the SVG dialogue, but we can not use the collection name without "sanitising" it.

**Comment by ghtmtt** [comment]
Got it. But, I don't know if there is already a library to de-asciify characters, but IMHO it is a very import missing feature of the plugin. In Windows we are facing this problem from time to time (like the last Bucuresti release).

If there isn't an easy fix QGIS side, then maybe the solution to convert the characters could be good.

**Comment by havatv** [comment]
I will definitely try to look more into this, but am a bit busy this week.
Ideas on how to solve this are welcome!

**Comment by havatv** [comment]
sanitize_filename from the pathvalidate package might help up.

**Comment by havatv** [comment]
@ghtmtt, could you install and check the proposed solution - zip-file: https://github.com/QGIS-Contribution/QGIS-ResourceSharing/archive/collection_directory_name.zip

**Comment by ghtmtt** [comment]
It works just perfectly! I'm testing it on a Linux (Debian) machine, not on Windows. But I really really think this is the path to follow. The user downloads some collection and find the collection (in SVG folder or wherever) with the same name.

>  This means that we should require repositories to have unique names.

This is maybe easier to check (or to put as a mandatory requirement). I think that I'd change the name of my repository if there is another one with the same name, so that other users can find *my* collections easier. What do you think?

BTW: **thanks**!

**Comment by havatv** [comment]
> > This means that we should require repositories to have unique names.
> 
> This is maybe easier to check (or to put as a mandatory requirement). I think that I'd change the name of my repository if there is another one with the same name, so that other users can find _my_ collections easier. What do you think?

I agree that requiring repository names to be unique is reasonable. But we then should make sure that those with merge rights for qgis/QGIS-Resources on github know about this.
Do you have an opinion on this, @anitagraser, @elpaso? Any others that should be asked?

**Comment by ghtmtt** [comment]
> I agree that requiring repository names to be unique is reasonable. But we then should make sure that those with merge rights for qgis/QGIS-Resources on github know about this.

I think we can set up a github action (no idea how to do it) that checks this in the `directory.csv` file.

What could be a potential conflicts is when an user loads a repository not published that has the same name.

**Comment by havatv** [comment]
> What could be a potential conflicts is when an user loads a repository not published that has the same name.

It should be easy to avoid that users add repositories with non-unique names in the plugin using "Add repository" in Settings.

**Comment by ghtmtt** [comment]
> It should be easy to avoid that users add repositories with non-unique names in the plugin using "Add repository" in Settings.

Great!

I think there could be some potential cases to manage:

* shared repo and public repo with the same name, but the **shared** repo has been downloaded first. The user trying to add the private repo will be informed (and *forced*?) to change the private name in order to download it
* shared repo and public repo with the same name, but the **private** repo has been downloaded first. There are no conflicts but in the case that also the shared repo will be downloaded than the user (of course) cannot change the remote name of somebody else repository. 
* somebody what to share a repository with a name already taken, then a github action (whatever) should inform repo maintainers that the PR should be not merged
* 2 private repos with the same name..... 

What I think should **NOT** happen is overwriting existing resources: that would be a data loss.

**Comment by havatv** [comment]
I have now updated the code so that users can not add a repository that has the same name as an existing repository.

What is missing now is handling the situation where a repository is added to the official QGIS directory of repositories, and that repository has the same name (but different URL) as a repository that the user already has added.

**Comment by ghtmtt** [comment]
> I have now updated the code in the referenced PR so that users can not add a repository that has the same name as an existing repository.

how is this situation managed?

> What is missing now is handling the situation where a repository is added to the official QGIS directory of repositories, and that repository has the same name (but different URL) as a repository that the user already has added.

I really think this check should be performed in this repository https://github.com/qgis/QGIS-Resources and not by the plugin

**Comment by havatv** [comment]
> > I have now updated the code in the referenced PR so that users can not add a repository that has the same name as an existing repository.
> 
> how is this situation managed?

If the repository name is already used, the user will not be able to add the repository, and a warning message (`Repositories must have unique names!`) is emitted to inform the user.

> > What is missing now is handling the situation where a repository is added to the official QGIS directory of repositories, and that repository has the same name (but different URL) as a repository that the user already has added.
> 
> I really think this check should be performed in this repository https://github.com/qgis/QGIS-Resources and not by the plugin

This situation can not be handled in the *https://github.com/qgis/QGIS-Resources* repository, because we have no way of knowing about the existence of repositories that are not present in the directory of officially approved repositories. This can be repositories that are used within an organisation or only "published" to the user base of the resource.

**Comment by havatv** [comment]
> What I think should **NOT** happen is overwriting existing resources: that would be a data loss.

I guess that this means that if a user has added a repository (that is not listed among the officially approved ones in the directory of https://github.com/qgis/QGIS-Resources), that repository should be kept as it is if a repository with the same name is added to the official directory.
I think it would be nice to inform the user that the repository they have added is "masking" an officially approved repository that has the same name (but different URL).

**Comment by anitagraser** [comment]
> Do you have an opinion on this, @anitagraser, @elpaso? Any others that should be asked?

Sorry, I currently don't have the resources to contribute to this project.

**Comment by ghtmtt** [comment]
@havatv sorry for the delay. But thanks for your work! Do you plan to release a new version of the plugin soon with this and the other #109 fix? Thanks again!

**Comment by havatv** [comment]
> @havatv sorry for the delay. But thanks for your work! Do you plan to release a new version of the plugin soon with this and the other #109 fix? Thanks again!

Thank you for showing interest in the plugin, @ghtmtt. I plan to release a new version quite soon, but current master has not yet been tested on Windows, and there is still some polishing to do regarding the handling of the unique name for repositories constraint. I was also hoping @chleidersdorff could provide some more feedback on issue #91, to help determine what the problem is.

Thanks to input from @dude1756, the plugin now supports all the four types of elements in style/symbol XML files (only symbols and colour maps were supported earlier), and the general appearance of the resource sharing elements in Style Manager has improved. So there has been a significant number of improvements since the release of version 0.13.1.

**Comment by havatv** [comment]
> @havatv sorry for the delay. But thanks for your work! Do you plan to release a new version of the plugin soon with this and the other #109 fix? Thanks again!

After testing on Windows, version 0.14.0 has now been released, @ghtmtt.

**Comment by ghtmtt** [comment]
great! Thanks!
