### ISSUE TITLE
Importing style xml only works for symbols

### ISSUE THREAD

**Issue by dude1756** [QGIS-Contribution/QGIS-ResourceSharing#113]
Hi there,

I have created a style xml file in QGIS that includes following sections:
` <symbols>`
`colorramps/>`
` <textformats/>`
` <labelsettings>`
If I install this xml file via resourceSharing plugin this file is copied to that path: `%appdata%\QGIS\QGIS3\profiles\default\resource_sharing\collections\3121786cab29e00abe0c643c78fab504baafdfd0\symbol`
However, when you look at QGIS style manager, only symbols are properly imported, none of the other styling settings (color, textformat, label).
Is there a way to achieve this?

Thanks!

**Comment by havatv** [comment]
Thanks for reporting, @dude1756! I am not very familiar with that part of the code. Anyway, the documentation should be updated to describe current behaviour. And hopefully we will be able to support more aspects of styles some time in the future.

**Comment by dude1756** [comment]
Thanks for your quick response. Looking at the code, I think colorramps are implemented but not working in my case. A bug?

**Comment by havatv** [comment]
> Thanks for your quick response. Looking at the code, I think colorramps are implemented but not working in my case. A bug?

It is very probable that this is a bug.
I think I have verified that symbol "import" through the Resource Sharing plugin works, but how would I know that colorramps and the other stuff work?
As you may understand, I don't know much about the style mechanisms in QGIS, so if you would like to investigate this, you are very welcome!

**Comment by havatv** [comment]
I just created a test collection with a style-XML file containing only two colourmaps. After installing the collection using version 0.13.1 of the plugin, the colourmaps were available when clicking the "Color ramp" pulldown and choosing "All color ramps".
Are you experiencing a different behaviour, @dude1756 ?

**Comment by havatv** [comment]
Hi again!

PR #120 adds support for textformats and labelsettings. It would be great if you could download, install and test:
https://github.com/QGIS-Contribution/QGIS-ResourceSharing/archive/improve_style_support.zip

Here is a screenshot of the style manager that shows that all the four style elements will now become available.
![image](https://user-images.githubusercontent.com/1598812/79958706-8c70b400-8483-11ea-86fd-6dfc375200a6.png)

**Comment by dude1756** [comment]
Hey havatv, how cool is that - Thx. It's obviously working. In my case I have now 3 tags in the left panel, where 1st is empty, 2nd just contains symbols and 3rd all elements. Can you confirm that behaviour?

**Comment by havatv** [comment]
@dude1756, as you can see from the screenshot above, I only have one tag for the collection. The behaviour you are observing indicates that there are tags there that are the result of previous collection installs.
Did you clean up the tags in Style Manager before installing the collection?
To remove a tag, right-click on it in the left part of the Style Manager, and choose *Remove*.

**Comment by dude1756** [comment]
Ok, I've cleaned everything including cache and it works! Thanks a lot.

**Comment by havatv** [comment]
Thanks again for reporting, @dude1756!
