### ISSUE TITLE
Importing style xml leads to obsolete folders in QGIS style manager

### ISSUE THREAD

**Issue by dude1756** [QGIS-Contribution/QGIS-ResourceSharing#114]
Hi there,

when I install a style xml via ResourceSharing plugin, file is copied to this path:
`%appdata%\QGIS\QGIS3\profiles\default\resource_sharing\collections\3121786cab29e00abe0c643c78fab504baafdfd0\symbol`
In QGIS style manager there are two folders/tags in left window:
1.) [NAME of collection](3121786cab29e00abe0c643c78fab504baafdfd0) 
2.) [NAME of collection](3121786cab29e00abe0c643c78fab504baafdfd0)\[NAME in xml file]

Only second tag includes imported symbols. It seems that you can delete first one without any side effect but could creation during install be avoided?

Thanks.

**Comment by havatv** [comment]
Thanks again for reporting, @dude1756! As I have said before, I am not very familiar with that part of the code. But I will try to look into it.

**Comment by havatv** [comment]
I have tried to clean up and improve the code that has to do with adding symbols. With current master I see the following in the Style Manager when a collection with three XML files has been installed:

![image](https://user-images.githubusercontent.com/1598812/79914866-42a5b080-8426-11ea-8000-c0de5388f27c.png)

So, only one entry in the left window per XML file.  Could you try to install current master and see if you still have the same issue (remove all tags before installing the collection with the symbol XML file - removal is done by right-clicking the tag in the left window and choose ***Remove***).

**Comment by havatv** [comment]
According to https://github.com/QGIS-Contribution/QGIS-ResourceSharing/issues/113#issuecomment-617708463, this seems to be solved with #120.

**Comment by havatv** [comment]
Thanks again for reporting, @dude1756!
