### ISSUE TITLE
Downloads entire .git repository

### ISSUE THREAD

**Issue by jonathan-geoseer** [QGIS-Contribution/QGIS-ResourceSharing#137]
I just downloaded "Distance Measurement Styles". It took a suspiciously long time. It turns out it did the following:

**Correct things**
* Downloaded the "distance-measurements" directory

**Wrong things** (the bug parts).
* Downloaded the entire .git directory. 49.8MB(!)
* Downloaded everything in the repo, including the collections that I *did not ask for*.
* Despite the fact that I now clearly have *everything* from faunalia, the plugin is only showing me as having the Distance Measurements Styles.

I'd posit it should only download the files required.

**Comment by havatv** [comment]
> **Wrong things** (the bug parts).
> 
>     * Downloaded the entire .git directory. 49.8MB(!)

The plugin uses git (through dulwich/porcelain), and (unfortunately) git clone stores the complete repository locally. I also find this a bit of a waste, but have not looked into alternatives yet.

>     * Downloaded everything in the repo, including the collections that I _did not ask for_.
> 
>     * Despite the fact that I now clearly have _everything_ from faunalia, the plugin is only showing me as having the Distance Measurements Styles.

Everything is there, but you have to install the collection to make it available through the plugin.

> I'd posit it should only download the files required.

I can understand that.
Thank you for the feedback, @jonathan-geoseer.

**Comment by Guts** [comment]
Hi,

I'm diving into your project and I think there is a proper way to download the repository using the `depth` parameter from git clone, included into the dulwich lib:

https://github.com/dulwich/dulwich/blob/5c8b3272a5e864977214ad382e04ce65ac9642f9/dulwich/porcelain.py#L394

Not sure this is the only place where to set this option but at least at this line:

https://github.com/QGIS-Contribution/QGIS-ResourceSharing/blob/3aab6ea07690ce50a9c12f43295e2b9151ad8859/resource_sharing/repository_handler/remote_git_handler.py#L125-L127

Are you interested in a PR?

**Comment by havatv** [comment]
> Hi,
> 
> I'm diving into your project and I think there is a proper way to download the repository using the `depth` parameter from git clone, included into the dulwich lib:
> 
> https://github.com/dulwich/dulwich/blob/5c8b3272a5e864977214ad382e04ce65ac9642f9/dulwich/porcelain.py#L394
> 
> Not sure this is the only place where to set this option but at least at this line:
> 
> https://github.com/QGIS-Contribution/QGIS-ResourceSharing/blob/3aab6ea07690ce50a9c12f43295e2b9151ad8859/resource_sharing/repository_handler/remote_git_handler.py#L125-L127
> 
> Are you interested in a PR?

Thank you for your interest in the QGIS Resource sharing plugin, @Guts.

A PR would be most welcome. It would be nice if we could limit the downloads.
However, I am struggling with brain cancer, so my capacity for following up
is currently very limited. So I hope you can test this extensively.

Thanks again!

**Comment by havatv** [comment]
@Guts, perhaps we could make this user configurable (QgsSettings)
e.g RepoDepth

**Comment by Guts** [comment]
> 
> 
> @Guts, perhaps we could make this user configurable (QgsSettings)
> e.g RepoDepth

From my point of view, allowing the end-user to customize the software behavior is a good thing. However, first, we should be sure that it fits the expected behavior of the plugin and IMHO, the plugin's goal is not to allow the user perform advanced git operations but only to enjoy the versioning an d sync sides from git, no?

**Comment by havatv** [comment]
> > @Guts, perhaps we could make this user configurable (QgsSettings)
> > e.g RepoDepth
> 
> From my point of view, allowing the end-user to customize the software behavior is a good thing. However, first, we should be sure that it fits the expected behavior of the plugin and IMHO, the plugin's goal is not to allow the user perform advanced git operations but only to enjoy the versioning an d sync sides from git, no?

Agreed.

**Comment by havatv** [comment]
Fixed by #164
