### ISSUE TITLE
"Resources	Unknown before installation"

### ISSUE THREAD

**Issue by jonathan-geoseer** [QGIS-Contribution/QGIS-ResourceSharing#138]
Usability: I would suggest that:
"Resources | Unknown before installation"

should simply not be shown at all; it's meaningless. Only show the Resources item if it can be populated.

**Comment by havatv** [comment]
> Usability: I would suggest that:
> "Resources | Unknown before installation"
> 
> should simply not be shown at all; it's meaningless. Only show the Resources item if it can be populated.

@jonathan-geoseer, thank you so much for your interest in the QGIS Resource Sharing plugin, and thank you for this suggestion. I tried to fix this in pull request #143.
