### ISSUE TITLE
Usability - Order of Information; highlight abstract

### ISSUE THREAD

**Issue by jonathan-geoseer** [QGIS-Contribution/QGIS-ResourceSharing#140]
To the end user, I would expect the information to be important in this order:

_Title, Abstract, Tags, Image, URL, license._

It's unlikely a user cares who the author is, what their email address is (is that even GDPR compliant?).

So I'd suggest it may be worth re-ordering the items, and also making the abstract text bigger and more obvious. Right now it's very not obvious.

**Comment by havatv** [comment]
Thanks again, @jonathan-geoseer!

* In PR #143 have changed the order of the metadata items, and I have also moved the previews into the table.
* I am not sure that I understand what you mean with "making the abstract text bigger and more obvious". The description (I assume that is what you mean by "abstract") is currently rendered in normal text - how exactly would you like it?
* Regarding the author and email - this is part of the public metadata for the resource. I would think that resource / collection authors would like to get credit for their work.

**Comment by jonathan-geoseer** [comment]
@havatv  - thanks for the replies.
> I am not sure that I understand what you mean with "making the abstract text bigger and more obvious". The description (I assume that is what you mean by "abstract") is currently rendered in normal text - how exactly would you like it?

Yes, I mean the description.  This suggestion is because the first time I saw the page I couldn't see the description. It's "invisible" because it's not highlighted unlike all the other metadata. So I would suggest either have it under a sub item that says "description", or increase its font size. Or both.

>  I would think that resource / collection authors would like to get credit for their work.
Possibly, but lets be honest, the end user likely doesn't care. When was the last time you sat through a movies credits and actually read the credits? Precisely. :-) In relation to the GDPR, I suspect you need explicit opt-in permission from the person to do this.

**Comment by havatv** [comment]
> Yes, I mean the description. This suggestion is because the first time I saw the page I couldn't see the description. It's "invisible" because it's not highlighted unlike all the other metadata. So I would suggest either have it under a sub item that says "description", or increase its font size. Or both.

I have updated the PR (#143) and moved the description down into the table (first row). Is that an acceptable solution, @jonathan-geoseer ?

> Possibly, but lets be honest, the end user likely doesn't care. When was the last time you sat through a movies credits and actually read the credits? Precisely. :-) In relation to the GDPR, I suspect you need explicit opt-in permission from the person to do this.

I tend to be one of the few that often sits through movie credits... :-)
Regarding GDPR -  would removing the email address be a reasonable measure?

Thanks again for your interest in the plugin!

**Comment by akbargumbira** [comment]
@havatv regarding GDPR, I think another solution is to make email as optional (https://github.com/QGIS-Contribution/QGIS-ResourceSharing/issues/140) so that we can give the decision to the authors. IMO, email is still important for other users to contact the author for collaboration and stuff..
