### ISSUE TITLE
Refreshing the collections?

### ISSUE THREAD

**Issue by jonathan-geoseer** [QGIS-Contribution/QGIS-ResourceSharing#145]
I opened a QGIS instance 3 days ago. Since then the list of resources that I see hasn't changed.

However, since then, someone has added a new item (Font Awesome icons). There doesn't seem to be any refresh so it's impossible to see this without restarting QGIS.

**Comment by havatv** [comment]
Yes, current behaviour is to only check the directory when QGIS is started.
Would adding a button for reloading the directory solve this, @jonathan-geoseer?
