### ISSUE TITLE
Resources have all disappeared

### ISSUE THREAD

**Issue by jonathan-geoseer** [QGIS-Contribution/QGIS-ResourceSharing#146]
So, I restarted QGIS, and now QGIS ResourceSharing can only see one resource: Font Awesome icons under "All collections".

Installed collections is also empty, despite the fact it should have one item under it.

I ended up figuring it out - I needed to go to "settings -> Reload repositories", but it's not clear why. I would expect this to happen when QGIS starts up. Also, seems odd that all the collections completely disappeared.

**Comment by havatv** [comment]
Thanks for reporting, @jonathan-geoseer. I experienced the same strange behaviour.

**Comment by havatv** [comment]
No collections are currently vidiblr,snd yhe reload repositories button is gone from ***Settings***.
