### ISSUE TITLE
Add support for checklist resource type

### ISSUE THREAD

**Issue by ricardogsilva** [QGIS-Contribution/QGIS-ResourceSharing#151]
At Kartoza we have developed the [QGIS Dataset QA Workbench] plugin. 

This plugin is meant to aid performing Quality Assurance workflows on  geospatial datasets. Briefly, it allows users to select a checklist from a set of available checklists and then perform validation of datasets by going over the steps defined therein. This validation step can be automated (via running Processing algorithms) or manual, depending on each checklist step.

Checklists are defined in `.json` files and are loaded from the `checklists` directory under the user's QGIS profile directory. 

The main use cases that we foresee for this plugin involve sharing checklist files between users of the same organization (for example between *dev* and *qa* teams).

The plugin currently has its own sharing story, which works like this:

- Checklist creator creates a web service where she puts assorted checklist files.
- Checklist user then specifies the URL of this web service by configuring a new checklist provider inside the plugin's UI

We are interested in simplifying this custom checklist sharing workflow by adding support for the *checklist* resource type in QGIS Resource Sharing plugin. That would allow us to remove the custom sharing stuff from our  plugin.

Is this something that you'd approve?

If so, I will be glad to submit a PR with the necessary modifications to QGIS Resource Sharing plugin to support this new resource type.

[QGIS Dataset QA Workbench]: https://github.com/kartoza/qgis_dataset_qa_workbench/

**Comment by ricardogsilva** [comment]
I went ahead and opened a PR with the modifications

**Comment by ricardogsilva** [comment]
@havatv 
Thanks for merging this!

**Comment by ricardogsilva** [comment]
@havatv 

Would it be feasible to release a new version of the QGIS Resource Sharing plugin including this in the coming days?

**Comment by havatv** [comment]
> @havatv
> 
> Would it be feasible to release a new version of the QGIS Resource Sharing plugin including this in the coming days?

That was the plan. But I will polish a bit before release (there have been a number of updates since the latest release).
