### ISSUE TITLE
Define a license for this source code

### ISSUE THREAD

**Issue by Guts** [QGIS-Contribution/QGIS-ResourceSharing#173]
The repository is missing a license. @havatv let's pick one from 😄.

Reading https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository and https://choosealicense.com/, I would recommend:

- [ ] GPL 3
- [ ] MIT
- [ ] MPL

**Comment by havatv** [comment]
> The repository is missing a license. @havatv let's pick one from 😄.
> 
> Reading https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository and https://choosealicense.com/, I would recommend:
> 
> * [ ]  GPL 3
> * [ ]  MIT
> * [ ]  MPL

Fine by me.
