### ISSUE TITLE
Add Open Street Map repository

### ISSUE THREAD

**Issue by AuSpotter** [QGIS-Contribution/QGIS-ResourceSharing#218]
# Is your feature request related to a problem? Please describe

Some common symbology (not represented on other repositories) is missing in QGIS and the Resource Sharing plugin.

# Describe the solution you'd like

The Open Street Map repository has the icons which would be very useful. 
https://github.com/openstreetmap/map-icons

Could this be added?

**Comment by Guts** [comment]
To add a repository, it must comply with a specific structure as described into the documentation: https://qgis-contribution.github.io/QGIS-ResourceSharing/authoring/creating-repository.html

Sadly, the mentioned repository is not suitable.
