### ISSUE TITLE
Please place the resource sharing action into the QGIS settings menu

### ISSUE THREAD

**Issue by timlinux** [QGIS-Contribution/QGIS-ResourceSharing#28]

**Comment by akbargumbira** [comment]
May I know why this should be put in the settings menu?

Btw, I just looked at the iface class, there are only these APIs:
```
addPluginToDatabaseMenu
addPluginToMenu (added to Plugins menu)
addPluginToRasterMenu
addPluginToVectorMenu
addPluginToWebMenu
```

**Comment by anitagraser** [comment]
Imho, the idea was to put the plugin close to the Style Manager since they are closely related. I think this should happen at latest when we include Resource Sharing as a core plugin.

If plugins cannot add themselves to the Settings menu yet, we might have to add this to the API.

**Comment by havatv** [comment]
@anitagraser, do you know if something has been done to make the `Settings` menu available for plugins?

**Comment by havatv** [comment]
eAFAIK,this is not  yet possible.
Closing.Please reopen when the situation has changed.
