### ISSUE TITLE
HiDPI: collection description font is too small

### ISSUE THREAD

**Issue by elpaso** [QGIS-Contribution/QGIS-ResourceSharing#3]
Low priority: don't loose time on this now, leave it for final polishing.

On a 4K screen the font is too small (Qt4 QGIS)
![image](https://cloud.githubusercontent.com/assets/142164/16680300/d7a15350-44ed-11e6-8835-57f3bb4a11cd.png)

**Comment by havatv** [comment]
Hi, @elpaso. I have updated bootstrap to the most recent version.  It seems to avoid pixels for `font-size`, so my hope is that this fixes the HiDPI issues.

I don't have access to a HiDPI system.  Could you check current master (https://github.com/QGIS-Contribution/QGIS-ResourceSharing/archive/master.zip)?

If this does not work we will reopen the issue.

**Comment by elpaso** [comment]
@havatv I'll do but I'm a little busy right now.

**Comment by havatv** [comment]
@elpaso, any chance you could test if the font size is OK/better on HiDPI displays with this change (avoiding pixels for font size settings)?

**Comment by elpaso** [comment]
Hi, sorry for the delay

it's looking good:

![immagine](https://user-images.githubusercontent.com/142164/77727082-ce7c1680-6ff9-11ea-9c7a-ade63dc69d64.png)

**Comment by havatv** [comment]
Thanks a lot, @elpaso!
If you did not experience other problems, I guess we can soon "release" a new version with this (and the Dulwich update) included.
