### ISSUE TITLE
add processing models as resource

### ISSUE THREAD

**Issue by andreasplesch** [QGIS-Contribution/QGIS-ResourceSharing#42]
In addition to processing scripts, add also processing models as installable resources. Processing script collections may often have associated processing models which use the scripts.

**Comment by havatv** [comment]
@andreasplesch, if you still have interest in this, it would be great if you could test the model support.
If you do not have access to a repository for testing, you can use the one that is mentioned in the pull request (#42).

**Comment by andreasplesch** [comment]
Thanks for adding support. Let me find some time for testing. Should I use QGIS2 or QGIS3 ?

**Comment by havatv** [comment]
> Thanks for adding support. Let me find some time for testing. Should I use QGIS2 or QGIS3 ?

QGIS 3. I am not sure if the latest versions work on QGIS 2.
