### ISSUE TITLE
Error 32:  Process cannot access file on install of OSM Spatialite Googlemaps

### ISSUE THREAD

**Issue by hitzi** [QGIS-Contribution/QGIS-ResourceSharing#45]
![2017-09-28_12h07_59](https://user-images.githubusercontent.com/3956475/30961918-1e6b33ea-a448-11e7-9769-9dfa4e184339.png)
I can install several resources but not all for example osm spatlialite googlemaps fail with the message in the attachement:
Error 32: The Process can not access the file, because another process is using it.

Win7, 64bit
Qgis 2.18.13
QGIS Resource Sharing 0.5.1

**Comment by havatv** [comment]
Thanks for reporting, @hitzi. Much appreciated!
Does the problem persist with the latest version of the plugin (currently 0.9.0)?

**Comment by havatv** [comment]
Assuming that this is the same issue as reported in #80 and fixed with #81, I close the issue.
@hitzi, please reopen if #81 does not resolve this for you.
