### ISSUE TITLE
ImportError: No module named QtWebKitWidgets.QWebView

### ISSUE THREAD

**Issue by brylie** [QGIS-Contribution/QGIS-ResourceSharing#46]
When trying to install this plugin, I am getting an error:

```
ImportError: No module named QtWebKitWidgets.QWebView
```

What dependency do I need to install to resolve this issue? Are there plans to migrate to Qt5?

**Comment by havatv** [comment]
The plugin has been updated to work with QGIS 3 and QT 5.
@brylie, does this problem persist on QGIS 3 with the latest version of the plugin?

**Comment by brylie** [comment]
I haven't tried recently, but will take a look ASAP.

**Comment by brylie** [comment]
I was able to install the plugin in QGIS 3.10 :-)

**Comment by havatv** [comment]
Thanks for testing, @brylie!
