### ISSUE TITLE
QgsSymbolLayerV2Utils.loadSymbol does not load one symbol

### ISSUE THREAD

**Issue by akbargumbira** [QGIS-Contribution/QGIS-ResourceSharing#49]
I wildly commented this line https://github.com/akbargumbira/qgis_resources_sharing/blob/develop/test/test_symbol_xml_extractor.py#L32 so that all the unittests can pass and release a new version (supporting gogs and gitlab repository handler from @slarosa). 

But there is a bigger problem there that might be a problem in QGIS LTR. This line here https://github.com/akbargumbira/qgis_resources_sharing/blob/develop/resource_sharing/symbol_xml_extractor.py#L45 is to load a symbol from XML element. It failed to load one symbol from this xml here https://github.com/akbargumbira/qgis_resources_data/blob/master/collections/test_collection/symbol/various_symbols.xml. The symbol that can't be loaded is this one https://github.com/akbargumbira/qgis_resources_data/blob/master/collections/test_collection/symbol/various_symbols.xml#L83.  QgsSymbolLayerV2Utils.loadSymbol() for that symbol element gives None from sip API, so some fixes in QGIS is needed.

**Comment by slarosa** [comment]
Hi @akbargumbira, the test is failing because the arrow symbol layer was introduced as from 2.16 (Nodebo), so in 2.14 (LTR) it fails.

Anyway I just issued a PR with some change for the unittesting which add a check to fix this issue.
The PR is here #50

**Comment by havatv** [comment]
It seems as if this one can be closed. What do you say @akbargumbira?
