### ISSUE TITLE
Provide an installation summary after a successfull installation of a new collection

### ISSUE THREAD

**Issue by elpaso** [QGIS-Contribution/QGIS-ResourceSharing#6]
Something like:
- SVG installed: 123
- Symbols installed: 1234
  ...

Collection folder:
/home/xxx/.qgis2/symbology_sharing/collections/ed86f2b4406dbd2c9afce1da12436836a89d3a5b

**Comment by akbargumbira** [comment]
Ah yeah, this is going to be useful since the installation of the resources is 'silent' installation (in other words, if there is no directory for the resource, it will just pass the installation)
